import type { Holding } from "./portfolio";

export const DAD_HOLDINGS: Holding[] = [
  {
    id: "d-bn-btc",
    source: "binance-spot",
    kind: "exchange",
    symbol: "BTC",
    name: "比特幣",
    quantity: 0.02255543,
    snapshotValueTwd: 57232.86,
    snapshotPnlTwd: 6648.47,
    snapshotReturn: 0.1314,
    costTwd: 50584.39,
    priceKey: "BTC",
  },
  {
    id: "d-bn-sol",
    source: "binance-spot",
    kind: "exchange",
    symbol: "SOL",
    name: "Solana",
    quantity: 1.1014198,
    snapshotValueTwd: 3737.51,
    snapshotPnlTwd: 406.83,
    snapshotReturn: 0.1221,
    costTwd: 3330.68,
    priceKey: "SOL",
  },
  {
    id: "d-bn-bnb",
    source: "binance-spot",
    kind: "exchange",
    symbol: "BNB",
    name: "BNB",
    quantity: 0.1467489,
    snapshotValueTwd: 3301.41,
    snapshotPnlTwd: -240.49,
    snapshotReturn: -0.0679,
    costTwd: 3541.9,
    priceKey: "BNB",
  },
  {
    id: "d-bn-sui",
    source: "binance-spot",
    kind: "exchange",
    symbol: "SUI",
    name: "Sui",
    quantity: 96.53468648,
    snapshotValueTwd: 2397.48,
    snapshotPnlTwd: -908.76,
    snapshotReturn: -0.2749,
    costTwd: 3306.24,
    priceKey: "SUI",
  },
  {
    id: "d-bn-usdt",
    source: "binance-spot",
    kind: "exchange",
    symbol: "USDT",
    name: "Tether",
    quantity: 67.05997484,
    snapshotValueTwd: 2125.13,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: 2125.13,
    priceKey: "USDT",
  },
  {
    id: "d-bn-spcxb",
    source: "binance-spot",
    kind: "exchange",
    symbol: "SPCXB",
    name: "SpaceX 股票代幣",
    quantity: 0.13405372,
    snapshotValueTwd: 594.19,
    snapshotPnlTwd: 0,
    snapshotReturn: 0,
    costTwd: 594.19,
    priceKey: "SPCXB",
  },
  {
    id: "d-bn-crclb",
    source: "binance-spot",
    kind: "exchange",
    symbol: "CRCLB",
    name: "Circle 股票代幣",
    quantity: 0.11,
    snapshotValueTwd: 329.34,
    snapshotPnlTwd: 30.36,
    snapshotReturn: 0.1015,
    costTwd: 298.98,
    priceKey: "CRCLB",
  },
  {
    id: "d-bn-tslab",
    source: "binance-spot",
    kind: "exchange",
    symbol: "TSLAB",
    name: "Tesla 股票代幣",
    quantity: 0.026,
    snapshotValueTwd: 289.32,
    snapshotPnlTwd: -25.25,
    snapshotReturn: -0.0803,
    costTwd: 314.57,
    priceKey: "TSLAB",
  },
  {
    id: "d-bn-usdc",
    source: "binance-spot",
    kind: "exchange",
    symbol: "USDC",
    name: "USD Coin",
    quantity: 0.88989823,
    snapshotValueTwd: 28.2,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: 28.2,
    priceKey: "USDC",
  },
  {
    id: "d-bn-doge",
    source: "binance-spot",
    kind: "exchange",
    symbol: "DOGE",
    name: "狗狗幣",
    quantity: 5.00489524,
    snapshotValueTwd: 14.11,
    snapshotPnlTwd: 14.11,
    snapshotReturn: null,
    costTwd: 0,
    priceKey: "DOGE",
  },
  {
    id: "d-bn-shib",
    source: "binance-spot",
    kind: "exchange",
    symbol: "SHIB",
    name: "SHIBA INU",
    quantity: 4984.29,
    snapshotValueTwd: 0.86,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: null,
    priceKey: "SHIB",
    hidden: true,
  },
  {
    id: "d-bn-sxt",
    source: "binance-spot",
    kind: "exchange",
    symbol: "SXT",
    name: "Space and Time",
    quantity: 2.7478692,
    snapshotValueTwd: 0.74,
    snapshotPnlTwd: 0.74,
    snapshotReturn: null,
    costTwd: 0,
    priceKey: "SXT",
    hidden: true,
  },
  {
    id: "d-bn-artx",
    source: "binance-spot",
    kind: "exchange",
    symbol: "ARTX",
    name: "ULTILAND",
    quantity: 0.13139,
    snapshotValueTwd: 0.55,
    snapshotPnlTwd: -0.53,
    snapshotReturn: -0.4937,
    costTwd: 1.08,
    priceKey: "ARTX",
    hidden: true,
  },
  {
    id: "d-bn-genius",
    source: "binance-spot",
    kind: "exchange",
    symbol: "GENIUS",
    name: "Genius Terminal",
    quantity: 0.0552128,
    snapshotValueTwd: 0.53,
    snapshotPnlTwd: 0.53,
    snapshotReturn: null,
    costTwd: 0,
    priceKey: "GENIUS",
    hidden: true,
  },
  {
    id: "d-bn-ada",
    source: "binance-spot",
    kind: "exchange",
    symbol: "ADA",
    name: "Cardano",
    quantity: 0.03247373,
    snapshotValueTwd: 0.22,
    snapshotPnlTwd: 0.22,
    snapshotReturn: null,
    costTwd: 0,
    priceKey: "ADA",
    hidden: true,
  },
  {
    id: "d-bn-act",
    source: "binance-spot",
    kind: "exchange",
    symbol: "ACT",
    name: "Act I",
    quantity: 0.5,
    snapshotValueTwd: 0.18,
    snapshotPnlTwd: 0.18,
    snapshotReturn: null,
    costTwd: 0,
    priceKey: "ACT",
    hidden: true,
  },
  {
    id: "d-w3-bnb",
    source: "binance-web3",
    kind: "wallet",
    symbol: "BNB",
    name: "BNB",
    quantity: 0.0049462,
    snapshotValueTwd: 108.19,
    snapshotPnlTwd: null,
    snapshotReturn: -0.0162,
    costTwd: null,
    priceKey: "BNB",
  },
  {
    id: "d-bg-eth",
    source: "bitget-spot",
    kind: "exchange",
    symbol: "ETH",
    name: "以太幣",
    quantity: 0.20993292,
    snapshotValueTwd: 16240.87,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: null,
    priceKey: "ETH",
  },
  {
    id: "d-bg-usdc",
    source: "bitget-spot",
    kind: "exchange",
    symbol: "USDC",
    name: "USD Coin",
    quantity: 151.95796609,
    snapshotValueTwd: 4807.16,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: 4807.16,
    priceKey: "USDC",
  },
  {
    id: "d-bg-usdt",
    source: "bitget-spot",
    kind: "exchange",
    symbol: "USDT",
    name: "Tether",
    quantity: 58.63101204,
    snapshotValueTwd: 1854.96,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: 1854.96,
    priceKey: "USDT",
  },
  {
    id: "d-mx-usdc",
    source: "mexc",
    kind: "exchange",
    symbol: "USDC",
    name: "USD Coin",
    quantity: 300.9252077,
    snapshotValueTwd: 9539.76,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: 9539.76,
    priceKey: "USDC",
  },
  {
    id: "d-mx-usdt",
    source: "mexc",
    kind: "exchange",
    symbol: "USDT",
    name: "Tether",
    quantity: 210.20836029,
    snapshotValueTwd: 6663.71,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: 6663.71,
    priceKey: "USDT",
  },
  {
    id: "d-mx-usd1",
    source: "mexc",
    kind: "exchange",
    symbol: "USD1",
    name: "USD1",
    quantity: 200.04,
    snapshotValueTwd: 6340.67,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: 6340.67,
    priceKey: "USD1",
  },
  {
    id: "d-mx-spacex",
    source: "mexc",
    kind: "exchange",
    symbol: "SPACEXPRE",
    name: "SpaceX 預上市",
    quantity: 0.00428175,
    snapshotValueTwd: 18.81,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: null,
    priceKey: null,
  },
  {
    id: "d-mx-wlfi",
    source: "mexc",
    kind: "exchange",
    symbol: "WLFI",
    name: "WLFI",
    quantity: 0.00957014,
    snapshotValueTwd: 0.017,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: null,
    priceKey: "WLFI",
    hidden: true,
  },
  {
    id: "d-mx-mon",
    source: "mexc",
    kind: "exchange",
    symbol: "MON",
    name: "MON",
    quantity: 0.0070762,
    snapshotValueTwd: 0.0063,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: null,
    priceKey: "MON",
    hidden: true,
  },
  {
    id: "d-mx-node",
    source: "mexc",
    kind: "exchange",
    symbol: "NODE",
    name: "NODE",
    quantity: 0.00156,
    snapshotValueTwd: 0.00029,
    snapshotPnlTwd: null,
    snapshotReturn: null,
    costTwd: null,
    priceKey: "NODE",
    hidden: true,
  },
];
